baseURL = "https://blog.example.com/"
languageCode = "en-us"
title = "The Melitix Blog"

theme = "m10c"

paginate = 5

[params]
  author = "Ricardo N Feliciano"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Melitix"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
