baseURL: "https://blog.example.com/"
languageCode: "en-us"
title: "The Melitix Blog"

theme: "m10c"

paginate: 5

params:
  author: "Ricardo N Feliciano"
  description: "We write about creating, organizing, and hosting meetups."
  avatar: "/img/avatar.png"
  social:
    - name: "twitter"
      url: "https://twitter.com/Melitix"
    - name: "facebook"
      url: "https://www.facebook.com/MelitixHQ"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
